name: expense_tracker
description: Advanced Expense Tracker with Enhanced UI and Analytics
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  equatable: ^2.0.5
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.0.11
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/localization/en.json
    - assets/localization/es.json
    - assets/onboarding_wallet.png
