name: expenses_tracker
description: A very advanced BudgetCalc Expense Tracker app with modern UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  intl: ^0.18.0
  uuid: ^3.0.6
  build_runner: ^2.3.3
  hive_generator: ^1.1.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
   

flutter:
  uses-material-design: true
  assets: 
    - assets/
    
